name: payment_intent
description: Stripe Payment Intent Test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  cloud_firestore: ^1.0.7
  # cloud_functions: ^1.1.1
  firebase_core: ^1.3.0
  http: ^0.13.3
  # stripe_payment: ^1.0.11
  flutter_stripe: ^1.0.2
  pay: ^1.0.1

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true